import { TaskTemplate } from "../types";

export const TASK_LIBRARY: TaskTemplate[] = [
  // ─────────── Movement (運動) ───────────
  {
    id: "mov-stretch-morning",
    category: "movement",
    difficulty: 1,
    emoji: "🌅",
    title: "起床後伸展 5 分鐘",
    description: "頸肩、腰、腿輕輕拉一拉，叫醒身體就好。",
    estimatedMinutes: 5,
  },
  {
    id: "mov-stand-up",
    category: "movement",
    difficulty: 1,
    emoji: "🪑",
    title: "每小時起身活動 2 分鐘 × 3 次",
    description: "走兩圈、伸展，避免久坐。",
  },
  {
    id: "mov-walk-after-meal-5",
    category: "movement",
    difficulty: 1,
    emoji: "🚶",
    title: "飯後散步 5 分鐘",
    description: "降血糖、減負擔，最簡單的開始。",
    estimatedMinutes: 5,
  },
  {
    id: "mov-walk-after-meal-10",
    category: "movement",
    difficulty: 2,
    emoji: "🚶",
    title: "飯後散步 10 分鐘",
    description: "強度低，但效果累積驚人。",
    estimatedMinutes: 10,
  },
  {
    id: "mov-walk-after-meal-15",
    category: "movement",
    difficulty: 3,
    emoji: "🚶",
    title: "飯後散步 15 分鐘",
    description: "兩餐後都做更好。",
    estimatedMinutes: 15,
  },
  {
    id: "mov-steps-3000",
    category: "movement",
    difficulty: 1,
    emoji: "👣",
    title: "今日走滿 3000 步",
    description: "在家附近走兩圈就差不多了。",
  },
  {
    id: "mov-steps-5000",
    category: "movement",
    difficulty: 2,
    emoji: "👣",
    title: "今日走滿 5000 步",
  },
  {
    id: "mov-steps-8000",
    category: "movement",
    difficulty: 3,
    emoji: "👣",
    title: "今日走滿 8000 步",
  },
  {
    id: "mov-chair-leg-raise",
    category: "movement",
    difficulty: 1,
    emoji: "🦵",
    title: "椅子上抬腿 10 下 × 3 組",
    description: "坐著就能做，膝蓋友善。",
  },
  {
    id: "mov-wall-pushup",
    category: "movement",
    difficulty: 2,
    emoji: "💪",
    title: "牆推 10 下 × 2 組",
    description: "比伏地挺身溫和，先建立感覺。",
  },
  {
    id: "mov-squat-10",
    category: "movement",
    difficulty: 2,
    emoji: "🏋️",
    title: "深蹲 10 下 × 2 組",
    excludeFor: ["knee-issue"],
  },
  {
    id: "mov-squat-15",
    category: "movement",
    difficulty: 3,
    emoji: "🏋️",
    title: "深蹲 15 下 × 3 組",
    excludeFor: ["knee-issue"],
  },
  {
    id: "mov-indoor-15",
    category: "movement",
    difficulty: 2,
    emoji: "🏠",
    title: "室內活動身體 15 分鐘",
    description: "跟著影片動一動、邊看劇邊踏步都算。",
    estimatedMinutes: 15,
  },
  {
    id: "mov-liss-20",
    category: "movement",
    difficulty: 3,
    emoji: "🚴",
    title: "LISS 有氧 20 分鐘",
    description: "心跳能講話的程度，散步快走或騎車都行。",
    estimatedMinutes: 20,
  },
  {
    id: "mov-stairs",
    category: "movement",
    difficulty: 2,
    emoji: "🪜",
    title: "今天用樓梯取代電梯",
    excludeFor: ["knee-issue"],
  },

  // ─────────── Diet (飲食) ───────────
  {
    id: "diet-water-before-meal",
    category: "diet",
    difficulty: 1,
    emoji: "💧",
    title: "一餐前喝一杯水",
    description: "幫助控制份量。",
  },
  {
    id: "diet-veg-first",
    category: "diet",
    difficulty: 1,
    emoji: "🥬",
    title: "一餐先吃菜再吃飯",
    description: "穩血糖、增加飽足感。",
  },
  {
    id: "diet-smaller-bowl",
    category: "diet",
    difficulty: 1,
    emoji: "🥣",
    title: "用小一號的碗",
    description: "份量自然減少，但視覺不會空。",
  },
  {
    id: "diet-photo-lunch",
    category: "diet",
    difficulty: 1,
    emoji: "📷",
    title: "拍下今天的午餐",
    description: "存著看看一週的飲食模式。",
  },
  {
    id: "diet-chopstick-down",
    category: "diet",
    difficulty: 2,
    emoji: "🥢",
    title: "吃飯時放下筷子 3 次",
    description: "強迫自己慢下來，飽足訊號才追得上。",
  },
  {
    id: "diet-no-sugar-drink",
    category: "diet",
    difficulty: 2,
    emoji: "🚫",
    title: "今天不喝含糖飲料",
    description: "改喝水、無糖茶。",
  },
  {
    id: "diet-no-snack-afternoon",
    category: "diet",
    difficulty: 2,
    emoji: "🍫",
    title: "下午不吃零食",
  },
  {
    id: "diet-fullness-rating",
    category: "diet",
    difficulty: 2,
    emoji: "🎯",
    title: "寫下午餐吃到幾分飽",
    description: "理想：七分飽就停。",
  },
  {
    id: "diet-chew-slow",
    category: "diet",
    difficulty: 2,
    emoji: "🐢",
    title: "細嚼慢嚥（每口 20 下以上）",
  },
  {
    id: "diet-record-all",
    category: "diet",
    difficulty: 3,
    emoji: "📝",
    title: "全天記錄每一餐吃了什麼",
  },
  {
    id: "diet-no-refined-carb",
    category: "diet",
    difficulty: 3,
    emoji: "🌾",
    title: "一餐改吃糙米/全麥/地瓜代替白飯白麵",
  },
  {
    id: "diet-no-eating-out",
    category: "diet",
    difficulty: 3,
    emoji: "🏡",
    title: "今天三餐至少一餐自己準備",
  },

  // ─────────── Sleep (作息) ───────────
  {
    id: "sleep-log-time",
    category: "sleep",
    difficulty: 1,
    emoji: "🕐",
    title: "睡前在日誌寫下幾點上床",
  },
  {
    id: "sleep-by-11",
    category: "sleep",
    difficulty: 2,
    emoji: "🌙",
    title: "晚上 11 點前躺床",
  },
  {
    id: "sleep-no-phone-30",
    category: "sleep",
    difficulty: 2,
    emoji: "📵",
    title: "睡前 30 分鐘不碰手機",
  },
  {
    id: "sleep-wake-7",
    category: "sleep",
    difficulty: 2,
    emoji: "☀️",
    title: "早上 7 點前起床",
    excludeFor: ["late-sleeper"],
  },
  {
    id: "sleep-by-11-streak",
    category: "sleep",
    difficulty: 3,
    emoji: "🌙",
    title: "連續兩天 11 點前躺床",
  },
  {
    id: "sleep-warm-water",
    category: "sleep",
    difficulty: 1,
    emoji: "☕",
    title: "睡前喝一杯溫水",
  },
  {
    id: "sleep-nap-max-20",
    category: "sleep",
    difficulty: 1,
    emoji: "💤",
    title: "中午小睡 20 分鐘以內",
    description: "太久反而會影響晚上。",
  },

  // ─────────── Hydration (補水) ───────────
  {
    id: "hydra-wake-500",
    category: "hydration",
    difficulty: 1,
    emoji: "🥤",
    title: "起床先喝 500ml 水",
  },
  {
    id: "hydra-bottle-out",
    category: "hydration",
    difficulty: 1,
    emoji: "🍶",
    title: "出門帶水壺",
  },
  {
    id: "hydra-1500",
    category: "hydration",
    difficulty: 2,
    emoji: "💧",
    title: "今天喝滿 1500ml 水",
  },
  {
    id: "hydra-2000",
    category: "hydration",
    difficulty: 3,
    emoji: "💧",
    title: "今天喝滿 2000ml 水",
  },
  {
    id: "hydra-before-each-meal",
    category: "hydration",
    difficulty: 2,
    emoji: "🥛",
    title: "每餐前喝一杯水",
  },
  {
    id: "hydra-water-only",
    category: "hydration",
    difficulty: 3,
    emoji: "🚰",
    title: "今天只喝水跟無糖茶",
  },

  // ─────────── Mental (心理) ───────────
  {
    id: "mental-breath-before-snack",
    category: "mental",
    difficulty: 1,
    emoji: "🌬️",
    title: "想吃零食前先深呼吸 5 次",
    description: "通常 90 秒過後衝動會降低。",
  },
  {
    id: "mental-affirm-one",
    category: "mental",
    difficulty: 1,
    emoji: "✨",
    title: "寫一句今天值得肯定自己的事",
  },
  {
    id: "mental-praise-self",
    category: "mental",
    difficulty: 1,
    emoji: "🤍",
    title: "對自己說一句鼓勵的話",
  },
  {
    id: "mental-mirror",
    category: "mental",
    difficulty: 2,
    emoji: "🪞",
    title: "對著鏡子說一句喜歡自己的話",
  },
  {
    id: "mental-mood-write",
    category: "mental",
    difficulty: 2,
    emoji: "💭",
    title: "用一段話寫下今天的心情",
  },
  {
    id: "mental-meditate-5",
    category: "mental",
    difficulty: 2,
    emoji: "🧘",
    title: "靜坐或冥想 5 分鐘",
    description: "用 app 或單純閉眼觀察呼吸都行。",
    estimatedMinutes: 5,
  },

  // ─────────── Reflection (反思) ───────────
  {
    id: "ref-trigger-moment",
    category: "reflection",
    difficulty: 2,
    emoji: "🔍",
    title: "寫今天最容易破功的時刻",
    description: "知道地雷在哪才能避開。",
  },
  {
    id: "ref-next-week",
    category: "reflection",
    difficulty: 2,
    emoji: "📅",
    title: "想一件下週要改善的事",
  },
  {
    id: "ref-200-word-journal",
    category: "reflection",
    difficulty: 3,
    emoji: "📖",
    title: "寫一篇 200 字的減脂日記",
  },
  {
    id: "ref-emotion-trigger",
    category: "reflection",
    difficulty: 3,
    emoji: "📌",
    title: "記錄今天的情緒觸發點（什麼時候想吃東西）",
  },
  {
    id: "ref-review-meals",
    category: "reflection",
    difficulty: 2,
    emoji: "🍽️",
    title: "今晚回顧今天的飲食有什麼可以調整",
  },
];

export function getTaskTemplate(id: string): TaskTemplate | undefined {
  return TASK_LIBRARY.find((t) => t.id === id);
}
