import { TaskTemplate, UserProfile } from "../types";

function shiftTimeEarlier(hhmm: string, minutes: number): string {
  if (!hhmm || !/^\d{1,2}:\d{2}$/.test(hhmm)) return hhmm;
  const [h, m] = hhmm.split(":").map(Number);
  const total = h * 60 + m - minutes;
  const norm = ((total % (24 * 60)) + 24 * 60) % (24 * 60);
  const nh = Math.floor(norm / 60);
  const nm = norm % 60;
  return `${String(nh).padStart(2, "0")}:${String(nm).padStart(2, "0")}`;
}

function bedtimeTitle(profile: UserProfile, offsetMin: number): string {
  const base = profile.sleepTime ?? "23:00";
  const target = shiftTimeEarlier(base, offsetMin);
  return `今晚 ${target} 之前躺床（比你平常 ${base} 早 ${offsetMin} 分鐘）`;
}

export const TASK_LIBRARY: TaskTemplate[] = [
  // ═══════════════ NUTRITION ═══════════════

  // veg-first
  {
    id: "veg-first-l1",
    family: "veg-first",
    pillar: "nutrition",
    level: 1,
    emoji: "🥬",
    title: "午餐前先吃完一份蔬菜（半碗以上）再動主食",
    description: "穩血糖、增飽足感，最低門檻的飲食習慣改造。",
    friction: "low",
    verification: "self-report",
  },
  {
    id: "veg-first-l2",
    family: "veg-first",
    pillar: "nutrition",
    level: 2,
    emoji: "🥬",
    title: "中餐+晚餐都先吃完一份蔬菜再動主食",
    friction: "medium",
    verification: "self-report",
  },
  {
    id: "veg-first-l3",
    family: "veg-first",
    pillar: "nutrition",
    level: 3,
    emoji: "🥬",
    title: "三餐都先吃完一份蔬菜再動主食",
    friction: "high",
    verification: "self-report",
  },

  // protein-anchor
  {
    id: "protein-l1",
    family: "protein-anchor",
    pillar: "nutrition",
    level: 1,
    emoji: "🥚",
    title: "早餐加一份蛋白質（蛋/豆漿/雞胸/優格擇一）",
    description: "蛋白質是減脂時保肌肉、抗餓的關鍵槓桿。",
    friction: "low",
    verification: "self-report",
  },
  {
    id: "protein-l2",
    family: "protein-anchor",
    pillar: "nutrition",
    level: 2,
    emoji: "🥚",
    title: "早餐+晚餐都有一份明確的蛋白質",
    friction: "medium",
    verification: "self-report",
  },
  {
    id: "protein-l3",
    family: "protein-anchor",
    pillar: "nutrition",
    level: 3,
    emoji: "🥚",
    title: "三餐都有一份明確的蛋白質（手掌大小 ≈ 100g 熟重）",
    friction: "high",
    verification: "self-report",
  },

  // drink-swap
  {
    id: "drink-l1",
    family: "drink-swap",
    pillar: "nutrition",
    level: 1,
    emoji: "🥤",
    title: "今天一杯含糖飲料改成無糖（無糖茶/水/氣泡水）",
    description: "一杯手搖通常 30-50g 糖，等於 120-200 大卡。",
    friction: "low",
    verification: "self-report",
    excludeFor: ["diabetic"],
  },
  {
    id: "drink-l2",
    family: "drink-swap",
    pillar: "nutrition",
    level: 2,
    emoji: "🥤",
    title: "今天整天不喝任何含糖飲料",
    friction: "medium",
    verification: "self-report",
  },
  {
    id: "drink-l3",
    family: "drink-swap",
    pillar: "nutrition",
    level: 3,
    emoji: "🥤",
    title: "今天只喝水跟無糖茶（連咖啡都不加糖/奶精）",
    friction: "high",
    verification: "self-report",
  },

  // portion
  {
    id: "portion-l1",
    family: "portion",
    pillar: "nutrition",
    level: 1,
    emoji: "🥣",
    title: "用比平常小一號的碗吃晚餐",
    friction: "low",
    verification: "self-report",
  },
  {
    id: "portion-l2",
    family: "portion",
    pillar: "nutrition",
    level: 2,
    emoji: "🥣",
    title: "主食那一碗只裝七分滿，蔬菜跟蛋白質可以加",
    friction: "medium",
    verification: "self-report",
  },
  {
    id: "portion-l3",
    family: "portion",
    pillar: "nutrition",
    level: 3,
    emoji: "🥣",
    title: "先夾一半份量出來，吃完先停 5 分鐘再決定要不要續",
    description: "飽足訊號約 15-20 分鐘才追上來。",
    friction: "high",
    verification: "timer",
  },

  // meal-photo
  {
    id: "photo-l1",
    family: "meal-photo",
    pillar: "nutrition",
    level: 1,
    emoji: "📷",
    title: "拍一張午餐照，存著就好",
    friction: "low",
    verification: "photo",
  },
  {
    id: "photo-l2",
    family: "meal-photo",
    pillar: "nutrition",
    level: 2,
    emoji: "📷",
    title: "拍一餐照，心裡標出蛋白質/蔬菜/主食各佔多少",
    description: "理想比例：蔬菜佔一半、蛋白質 1/4、主食 1/4。",
    friction: "medium",
    verification: "photo",
  },
  {
    id: "photo-l3",
    family: "meal-photo",
    pillar: "nutrition",
    level: 3,
    emoji: "📷",
    title: "三餐都拍，週末翻一次找出可調整的模式",
    friction: "high",
    verification: "photo",
  },

  // slow-eating
  {
    id: "slow-l1",
    family: "slow-eating",
    pillar: "nutrition",
    level: 1,
    emoji: "🐢",
    title: "晚餐吃到一半放下筷子 1 分鐘，喝口水再繼續",
    friction: "low",
    verification: "timer",
  },
  {
    id: "slow-l2",
    family: "slow-eating",
    pillar: "nutrition",
    level: 2,
    emoji: "🐢",
    title: "晚餐每口咀嚼 15 下以上",
    friction: "medium",
    verification: "self-report",
  },
  {
    id: "slow-l3",
    family: "slow-eating",
    pillar: "nutrition",
    level: 3,
    emoji: "🐢",
    title: "三餐每餐都吃滿 20 分鐘以上",
    friction: "high",
    verification: "timer",
  },

  // carb-quality
  {
    id: "carb-l1",
    family: "carb-quality",
    pillar: "nutrition",
    level: 1,
    emoji: "🌾",
    title: "一餐主食換成糙米/全麥麵包/地瓜",
    friction: "low",
    verification: "self-report",
  },
  {
    id: "carb-l2",
    family: "carb-quality",
    pillar: "nutrition",
    level: 2,
    emoji: "🌾",
    title: "兩餐主食換成糙米/全麥/地瓜",
    friction: "medium",
    verification: "self-report",
  },
  {
    id: "carb-l3",
    family: "carb-quality",
    pillar: "nutrition",
    level: 3,
    emoji: "🌾",
    title: "今天不吃白飯白麵白吐司，全部換成原型澱粉",
    friction: "high",
    verification: "self-report",
  },

  // no-late-snack
  {
    id: "snack-l1",
    family: "no-late-snack",
    pillar: "nutrition",
    level: 1,
    emoji: "🍫",
    title: "下午 3 點不吃零食（嘴饞先喝水或刷牙）",
    friction: "low",
    verification: "self-report",
  },
  {
    id: "snack-l2",
    family: "no-late-snack",
    pillar: "nutrition",
    level: 2,
    emoji: "🍫",
    title: "下午+睡前都不吃零食",
    friction: "medium",
    verification: "self-report",
  },
  {
    id: "snack-l3",
    family: "no-late-snack",
    pillar: "nutrition",
    level: 3,
    emoji: "🍫",
    title: "今天只在三餐吃，沒額外加餐",
    friction: "high",
    verification: "self-report",
  },

  // ═══════════════ MOVEMENT ═══════════════

  // post-meal-walk
  {
    id: "walk-l1",
    family: "post-meal-walk",
    pillar: "movement",
    level: 1,
    emoji: "🚶",
    title: "晚餐後 30 分鐘內，到樓下/巷口散步 5 分鐘",
    effortMinutes: 5,
    friction: "low",
    verification: "timer",
  },
  {
    id: "walk-l2",
    family: "post-meal-walk",
    pillar: "movement",
    level: 2,
    emoji: "🚶",
    title: "晚餐後 30 分鐘內散步 10 分鐘",
    effortMinutes: 10,
    friction: "medium",
    verification: "timer",
  },
  {
    id: "walk-l3",
    family: "post-meal-walk",
    pillar: "movement",
    level: 3,
    emoji: "🚶",
    title: "午餐+晚餐後各散步 15 分鐘",
    effortMinutes: 30,
    friction: "high",
    verification: "timer",
  },

  // daily-steps
  {
    id: "steps-l1",
    family: "daily-steps",
    pillar: "movement",
    level: 1,
    emoji: "👣",
    title: "今天累積走 3000 步",
    friction: "low",
    verification: "count",
  },
  {
    id: "steps-l2",
    family: "daily-steps",
    pillar: "movement",
    level: 2,
    emoji: "👣",
    title: "今天累積走 5000 步",
    friction: "medium",
    verification: "count",
  },
  {
    id: "steps-l3",
    family: "daily-steps",
    pillar: "movement",
    level: 3,
    emoji: "👣",
    title: "今天累積走 8000 步",
    friction: "high",
    verification: "count",
    excludeFor: ["knee-issue"],
  },

  // neat-boost
  {
    id: "neat-l1",
    family: "neat-boost",
    pillar: "movement",
    level: 1,
    emoji: "🪑",
    title: "每小時起身活動 2 分鐘，今天做到 3 次",
    friction: "medium",
    verification: "count",
  },
  {
    id: "neat-l2",
    family: "neat-boost",
    pillar: "movement",
    level: 2,
    emoji: "🪑",
    title: "久坐超過 50 分鐘就站起來走一圈，今天做到 5 次",
    friction: "medium",
    verification: "count",
  },
  {
    id: "neat-l3",
    family: "neat-boost",
    pillar: "movement",
    level: 3,
    emoji: "🪜",
    title: "今天樓梯全程取代電梯",
    friction: "high",
    verification: "self-report",
    excludeFor: ["knee-issue"],
  },

  // low-impact-strength
  {
    id: "strength-l1",
    family: "low-impact-strength",
    pillar: "movement",
    level: 1,
    emoji: "💪",
    title: "牆推 10 下 × 2 組",
    friction: "low",
    verification: "count",
  },
  {
    id: "strength-l2",
    family: "low-impact-strength",
    pillar: "movement",
    level: 2,
    emoji: "🦵",
    title: "椅子上抬腿 10 下 × 3 組 + 牆推 10 下 × 2 組",
    friction: "medium",
    verification: "count",
  },
  {
    id: "strength-l3",
    family: "low-impact-strength",
    pillar: "movement",
    level: 3,
    emoji: "🏋️",
    title: "30 秒平板 ×3 + 牆推 ×15 ×3 + 椅子深蹲 ×10 ×3",
    friction: "high",
    verification: "count",
    excludeFor: ["back-issue"],
  },

  // ═══════════════ RECOVERY ═══════════════

  // bedtime-shift（動態：比平常早 N 分鐘）
  {
    id: "bedtime-l1",
    family: "bedtime-shift",
    pillar: "recovery",
    level: 1,
    emoji: "🌙",
    title: "比平常睡覺時間早 15 分鐘上床",
    friction: "low",
    verification: "self-report",
    buildTitle: (p) => bedtimeTitle(p, 15),
  },
  {
    id: "bedtime-l2",
    family: "bedtime-shift",
    pillar: "recovery",
    level: 2,
    emoji: "🌙",
    title: "比平常睡覺時間早 30 分鐘上床",
    friction: "medium",
    verification: "self-report",
    buildTitle: (p) => bedtimeTitle(p, 30),
  },
  {
    id: "bedtime-l3",
    family: "bedtime-shift",
    pillar: "recovery",
    level: 3,
    emoji: "🌙",
    title: "連續 3 晚比平常早 30 分鐘上床",
    friction: "high",
    verification: "self-report",
    buildTitle: (p) =>
      `連續 3 晚 ${shiftTimeEarlier(p.sleepTime ?? "23:00", 30)} 之前躺床`,
  },

  // device-free-night
  {
    id: "device-l1",
    family: "device-free-night",
    pillar: "recovery",
    level: 1,
    emoji: "📵",
    title: "睡前 30 分鐘把手機放到床外",
    friction: "low",
    verification: "self-report",
  },
  {
    id: "device-l2",
    family: "device-free-night",
    pillar: "recovery",
    level: 2,
    emoji: "📵",
    title: "睡前 60 分鐘把手機放到床外，看書或拉筋",
    friction: "medium",
    verification: "self-report",
  },
  {
    id: "device-l3",
    family: "device-free-night",
    pillar: "recovery",
    level: 3,
    emoji: "📵",
    title: "連續 5 晚做到睡前 30 分鐘無手機",
    friction: "high",
    verification: "self-report",
  },

  // stress-pause
  {
    id: "stress-l1",
    family: "stress-pause",
    pillar: "recovery",
    level: 1,
    emoji: "🌬️",
    title: "最想吃零食的瞬間，先喝水 + 等 10 分鐘再決定",
    description: "衝動通常 5-15 分鐘後會降下來。",
    friction: "medium",
    verification: "self-report",
  },
  {
    id: "stress-l2",
    family: "stress-pause",
    pillar: "recovery",
    level: 2,
    emoji: "🌬️",
    title: "今天最想破功的時候，寫下「是什麼觸發了我？」",
    friction: "medium",
    verification: "self-report",
  },
  {
    id: "stress-l3",
    family: "stress-pause",
    pillar: "recovery",
    level: 3,
    emoji: "🧘",
    title: "做 5 分鐘呼吸練習或靜坐",
    effortMinutes: 5,
    friction: "medium",
    verification: "timer",
  },

  // self-compassion
  {
    id: "compass-l1",
    family: "self-compassion",
    pillar: "recovery",
    level: 1,
    emoji: "✨",
    title: "寫一句今天值得肯定自己的事",
    friction: "low",
    verification: "self-report",
  },
  {
    id: "compass-l2",
    family: "self-compassion",
    pillar: "recovery",
    level: 2,
    emoji: "🪞",
    title: "對著鏡子說一句喜歡自己現在的話",
    friction: "medium",
    verification: "self-report",
  },
  {
    id: "compass-l3",
    family: "self-compassion",
    pillar: "recovery",
    level: 3,
    emoji: "🤍",
    title: "寫下 3 件今天做得不錯的事（不論大小）",
    friction: "medium",
    verification: "self-report",
  },

  // trigger-awareness
  {
    id: "trigger-l1",
    family: "trigger-awareness",
    pillar: "recovery",
    level: 1,
    emoji: "🔍",
    title: "寫下今天最想破功的 1 個瞬間（時間 + 觸發 + 後來怎麼處理）",
    friction: "medium",
    verification: "self-report",
  },
  {
    id: "trigger-l2",
    family: "trigger-awareness",
    pillar: "recovery",
    level: 2,
    emoji: "📌",
    title: "列出本週 3 個高風險時刻，明天起預先避開或預演",
    friction: "high",
    verification: "self-report",
  },
  {
    id: "trigger-l3",
    family: "trigger-awareness",
    pillar: "recovery",
    level: 3,
    emoji: "🔁",
    title: "為最高頻的觸發點寫 1 個替代方案（飯後想滑手機 → 散步 5 分鐘）",
    friction: "high",
    verification: "self-report",
  },

  // daily-journal
  {
    id: "journal-l1",
    family: "daily-journal",
    pillar: "recovery",
    level: 1,
    emoji: "📓",
    title: "在日誌寫一段話：今天吃得怎麼樣 / 動得怎麼樣",
    friction: "low",
    verification: "self-report",
  },
  {
    id: "journal-l2",
    family: "daily-journal",
    pillar: "recovery",
    level: 2,
    emoji: "📓",
    title: "在日誌寫 100 字以上，包含 1 個成功 + 1 個卡點",
    friction: "medium",
    verification: "self-report",
  },
  {
    id: "journal-l3",
    family: "daily-journal",
    pillar: "recovery",
    level: 3,
    emoji: "📖",
    title: "寫 200 字日記 + 替本週打分（1-10 分）",
    friction: "high",
    verification: "self-report",
  },

  // pre-meal-consult（飯前停一下）
  {
    id: "consult-l1",
    family: "pre-meal-consult",
    pillar: "nutrition",
    level: 1,
    emoji: "🤔",
    title: "吃飯前 30 秒問自己：「現在是真的餓還是嘴饞？」等 10 分鐘再決定",
    description: "嘴饞通常 10 分鐘後會降下來；真的餓就大方吃。",
    friction: "low",
    verification: "self-report",
  },
  {
    id: "consult-l2",
    family: "pre-meal-consult",
    pillar: "nutrition",
    level: 2,
    emoji: "🤔",
    title: "點餐/外送前先想 3 個更輕的替代品再決定",
    friction: "medium",
    verification: "self-report",
  },
  {
    id: "consult-l3",
    family: "pre-meal-consult",
    pillar: "nutrition",
    level: 3,
    emoji: "🤖",
    title: "重要外食前到「教練」頁諮詢一次再點餐",
    description: "把場景、預算、體感丟給 AI 教練，拿 2-3 個排序選項。",
    friction: "medium",
    verification: "self-report",
  },

  // ═══════════════ MORE RECOVERY ═══════════════

  // caffeine-cutoff
  {
    id: "caffeine-l1",
    family: "caffeine-cutoff",
    pillar: "recovery",
    level: 1,
    emoji: "☕",
    title: "下午 2 點之後不喝任何含咖啡因飲料（咖啡/茶/可樂）",
    description: "咖啡因半衰期 5-6 小時，下午 2 點喝晚上 11 點還剩一半。",
    friction: "low",
    verification: "self-report",
  },
  {
    id: "caffeine-l2",
    family: "caffeine-cutoff",
    pillar: "recovery",
    level: 2,
    emoji: "☕",
    title: "中午 12 點之後不喝任何含咖啡因飲料",
    friction: "medium",
    verification: "self-report",
  },
  {
    id: "caffeine-l3",
    family: "caffeine-cutoff",
    pillar: "recovery",
    level: 3,
    emoji: "☕",
    title: "連續 7 天下午 2 點後 caffeine-free + 睡前 3 小時不喝酒",
    friction: "high",
    verification: "self-report",
  },

  // morning-light
  {
    id: "light-l1",
    family: "morning-light",
    pillar: "recovery",
    level: 1,
    emoji: "🌞",
    title: "起床後 1 小時內，在窗邊或陽台曬 10 分鐘自然光",
    description: "校準生理時鐘最有力的單一手段。",
    effortMinutes: 10,
    friction: "low",
    verification: "timer",
  },
  {
    id: "light-l2",
    family: "morning-light",
    pillar: "recovery",
    level: 2,
    emoji: "🌞",
    title: "起床後 1 小時內，戶外曬 15 分鐘自然光（陽台或巷口）",
    effortMinutes: 15,
    friction: "medium",
    verification: "timer",
  },
  {
    id: "light-l3",
    family: "morning-light",
    pillar: "recovery",
    level: 3,
    emoji: "🚶",
    title: "起床後出門散步 15 分鐘（光 + 動一起做）",
    effortMinutes: 15,
    friction: "medium",
    verification: "timer",
  },

  // pre-sleep-routine
  {
    id: "presleep-l1",
    family: "pre-sleep-routine",
    pillar: "recovery",
    level: 1,
    emoji: "🛁",
    title: "睡前 60-90 分鐘洗熱水澡或泡腳 10 分鐘",
    description: "洗完後身體散熱，核心體溫下降幫助入睡。",
    effortMinutes: 10,
    friction: "low",
    verification: "self-report",
  },
  {
    id: "presleep-l2",
    family: "pre-sleep-routine",
    pillar: "recovery",
    level: 2,
    emoji: "🧘",
    title: "睡前做 5 分鐘伸展/拉筋（頸肩、髖、腿）",
    effortMinutes: 5,
    friction: "medium",
    verification: "timer",
  },
  {
    id: "presleep-l3",
    family: "pre-sleep-routine",
    pillar: "recovery",
    level: 3,
    emoji: "📝",
    title: "睡前儀式三件套：暖光 + 紙本書 10 分鐘 + 寫擔心清單",
    description: "把腦中盤旋的事寫下來，告訴大腦「已記下了不用再跑」。",
    friction: "high",
    verification: "self-report",
  },

  // ═══════════════ BONUS ═══════════════

  // hydration
  {
    id: "hydra-l1",
    family: "hydration",
    pillar: "bonus",
    level: 1,
    emoji: "💧",
    title: "起床先喝 500ml 水",
    friction: "low",
    verification: "self-report",
  },
  {
    id: "hydra-l2",
    family: "hydration",
    pillar: "bonus",
    level: 2,
    emoji: "💧",
    title: "今天累積喝滿 1500ml 水",
    friction: "medium",
    verification: "count",
  },
  {
    id: "hydra-l3",
    family: "hydration",
    pillar: "bonus",
    level: 3,
    emoji: "💧",
    title: "今天累積喝滿 2000ml 水（出門帶水壺）",
    friction: "high",
    verification: "count",
  },

  // environment-prep
  {
    id: "env-l1",
    family: "environment-prep",
    pillar: "bonus",
    level: 1,
    emoji: "🫣",
    title: "把家裡會破功的零食藏到不順手的地方（或丟掉）",
    description: "看不到、難拿到，衝動行為會自然少 60%。",
    friction: "low",
    verification: "self-report",
  },
  {
    id: "env-l2",
    family: "environment-prep",
    pillar: "bonus",
    level: 2,
    emoji: "🎒",
    title: "出門帶水壺 + 一份堅果（10g），避開便利商店",
    friction: "medium",
    verification: "self-report",
  },
  {
    id: "env-l3",
    family: "environment-prep",
    pillar: "bonus",
    level: 3,
    emoji: "🧊",
    title: "整理冰箱／櫥櫃：蔬果蛋白質放最前面、零食推最深處",
    friction: "high",
    verification: "self-report",
  },
];

export function getTaskTemplate(id: string): TaskTemplate | undefined {
  return TASK_LIBRARY.find((t) => t.id === id);
}
